try {
  throw 'error';
} catch  {
  console.log('catch error');
}